# Generated by Django 3.1.2 on 2020-10-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.IntegerField(choices=[(1, 'True'), (2, 'False'), (3, 'Other')])),
                ('text', models.CharField(max_length=2048)),
                ('citation_url', models.CharField(max_length=2048)),
                ('citation_title', models.CharField(max_length=2048)),
                ('credible_count', models.IntegerField()),
                ('not_credible_count', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
            ],
        ),
    ]
