# Generated by Django 3.1.2 on 2020-10-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Neither', 'Neither')], max_length=10),
        ),
    ]
