# Generated by Django 3.1.2 on 2020-10-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201017_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Neither', 'Neither')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(check=models.Q(answer__in=['True', 'False', 'Neither']), name='forum_answer_answer_valid'),
        ),
    ]
