# Generated by Django 3.2 on 2021-04-18 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_auto_20210407_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='citation_title',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='citation_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='citation_image_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='citation_title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='citation_url',
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=2048)),
                ('image_url', models.CharField(max_length=2048)),
                ('content_pk', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'forum'), ('model', 'answer')), models.Q(('app_label', 'forum'), ('model', 'question')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
