# Generated by Django 3.1.6 on 2021-04-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='credible_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='not_credible_count',
        ),
    ]
