URL_FORMAT_INVALID = "The citation url is not a valid url. Please remember to include the scheme (eg. https://)"
ANSWER_CHOICES_INVALID = "Answer must be True, False, or Neither"
QUESTION_ID_INVALID = "Ensure this Answer is created in response to a valid Question!"
QUESTION_ID_INVALID = "Ensure this Vote is created in response to a valid Answer!"
EMAIL_INVALID = "Email is invalid."
